Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 25
Layout/LineLength:
  Max: 200
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Bundler/OrderedGems:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'data/sample/**/*'
    - 'tmp/**/*'
