#!/usr/bin/env ruby

# frozen_string_literal: true

### Updating version

new_version = Time.now.strftime('%Y%m%d.%H%M%S.%L')

version_file = 'lib/data_modeller/version.rb'
if File.exist?(version_file)
  text = File.read(version_file)
  File.open(version_file, 'w') { |file| file << text.sub(/VERSION = '.+'/, "VERSION = '#{new_version}'") }
  system("git add #{version_file}")
end

gemfile = 'Gemfile.lock'
if File.exist?(gemfile)
  text = File.read(gemfile)
  File.open(gemfile, 'w') { |file| file << text.sub(/rails-data-modeller \([^)]+\)/, "rails-data-modeller (#{new_version})") }
  system("git add #{gemfile}")
end

### Verifying changes with rubocop

require 'rubocop'

ADDED_OR_MODIFIED = /A|AM|^M/

changes = `git status --porcelain`.split(/\n/)
changes.select! { |file_name_with_status| file_name_with_status =~ ADDED_OR_MODIFIED }
changed_files = changes.map { |file_name_with_status| file_name_with_status.split[1] }

ruby_files = changed_files.select { |file_name| File.extname(file_name) == '.rb' }
system("rubocop --force-exclusion #{ruby_files.join(' ')}") unless ruby_files.empty?

exit $CHILD_STATUS.to_s[-1].to_i
